apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-external-secret
  namespace: jerney-ns
  labels:
    app: jerney-backend
spec:
  refreshInterval: "1h" 
  secretStoreRef:
    name: aws-secretsmanager 
    kind: SecretStore 

  target:
    name: backend-secret 
    creationPolicy: Owner # ESO owns the created secret
    
  data:
    - secretKey: DB_NAME
      remoteRef:
        key: prod/jerney/backend
        property: DB_NAME
    
    - secretKey: DB_USER
      remoteRef:
        key: prod/jerney/backend
        property: DB_USER
    
    - secretKey: DB_PASSWORD
      remoteRef:
        key: prod/jerney/backend
        property: DB_PASSWORD
    