apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-external-secret
  namespace: jerney-ns
  labels:
    app: jerney-database
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: database-secret
    creationPolicy: Owner

  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: prod/jerney/database
        property: POSTGRES_USER

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: prod/jerney/database
        property: POSTGRES_PASSWORD

    - secretKey: POSTGRES_DB
      remoteRef:
        key: prod/jerney/database
        property: POSTGRES_DB
