apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jerney-app
  namespace: argocd
  
spec:
  project: jerney-project

  source:
    repoURL: "https://github.com/zohaibwarraich1/Jerney-real-time-blog-website.git"
    targetRevision: HEAD
    path: Jerney-real-time-blog-website-chart
    
    # Helm specific configuration
    helm:
      # Helm values files
      valueFiles:
        - values.yaml

  destination:
    server: {{ .Values.infrastructure.EKSclusterArn | default "https://kubernetes.default.svc" | quote }}
    namespace: {{ .Values.global.namespace | quote }}

  # Sync policy configuration
  syncPolicy:
    automated:
      prune: true
      # Enforces that Git is the single source of truth and undo manual changes in cluster.
      selfHeal: true
    syncOptions:
      # Auto-create 'retail-store-ns' if missing
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - Validate=true
      - SkipSchemaValidation=false
      - ApplyOutOfSyncOnly=false
    
    # Retry strategy for failed syncs
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Ignore differences at specific JSON paths
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas

  # Revision history limit
  revisionHistoryLimit: 10