apiVersion: v1
kind: Secret
metadata:
  name: argocd-cluster-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: "jerney-cluster"
  server: {{ .Values.infrastructure.EKSclusterArn | default "https://kubernetes.default.svc" | quote }}
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }