{{- if .Values.backendNetworkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.backendNetworkPolicy.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "Jerney-real-time-blog-website-chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.backendDeployment.podName }}
  
  policyTypes:
    - Ingress
    - Egress
  
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.frontendDeployment.podName }}
      ports:
        - protocol: TCP
          port: {{ .Values.backendService.port }}
  
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ .Values.databaseStatefulset.podName }}
      ports:
        - protocol: TCP
          port: {{ .Values.databaseService.port }}
    - to:
        - namespaceSelector: {}
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}