apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backendService.name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    {{- include "Jerney-real-time-blog-website-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backendService.type | quote }}
  selector:
    app: {{ .Values.backendDeployment.podName | quote }}
  ports:
    - name: tcp
      port: {{ .Values.backendService.port }}
      targetPort: {{ .Values.backendService.port }}
      protocol: TCP