apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backendConfig.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "Jerney-real-time-blog-website-chart.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.backendConfig.dbHost | quote }}
  DB_PORT: {{ .Values.backendConfig.dbPort | quote }}
  PGSSLMODE: "no-verify"  # RDS SSL required hai — no-verify certificate check skip karta hai (VPC internal)