apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.backendExternalSecret.name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    {{- include "Jerney-real-time-blog-website-chart.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.backendExternalSecret.spec.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.infrastructure.secretStore.name | quote }}
    kind: SecretStore
  target:
    name: {{ .Values.backendExternalSecret.spec.target.name | quote }}
    creationPolicy: Owner
  data:
    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.backendExternalSecret.remoteKey | quote }}
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.backendExternalSecret.remoteKey | quote }}
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.backendExternalSecret.remoteKey }}
        property: DB_PASSWORD