apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontendService.name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    {{- include "Jerney-real-time-blog-website-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontendService.type | quote }}
  selector:
    app: {{ .Values.frontendDeployment.podName | quote }}
  ports:
    - name: http
      port: {{ .Values.frontendService.port }}
      targetPort: {{ .Values.frontendService.port }}
      protocol: TCP
      {{- if eq .Values.frontendService.type "NodePort" }}
      nodePort: {{ .Values.frontendService.nodePort }}
      {{- end }}
