apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: jerney-ns
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      # AuthN: If using EKS via IRSA 
      auth:
        jwt:
          serviceAccountRef:
            name: eso-sa # The SA ESO runs with, linked to the IAM Role
            