apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.eks.amazonaws.com 
volumeBindingMode: WaitForFirstConsumer # PVC tab tak volume na banaye jab tak pod schedule na ho jaye
parameters:
  type: gp3 
  iops: "3000" 
  throughput: "125" 
