apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.databaseExternalSecret.name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    {{- include "Jerney-real-time-blog-website-chart.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.databaseExternalSecret.spec.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.infrastructure.secretStore.name | quote }}
    kind: SecretStore
  target:
    name: {{ .Values.databaseExternalSecret.spec.target.name | quote }}
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.databaseExternalSecret.remoteKey | quote }}
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.databaseExternalSecret.remoteKey | quote }}
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: {{ .Values.databaseExternalSecret.remoteKey }}
        property: POSTGRES_DB
