apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.databaseService.name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    {{- include "Jerney-real-time-blog-website-chart.labels" . | nindent 4 }}
spec:
  clusterIP: None # Headless
  selector:
    app: {{ .Values.databaseStatefulset.podName | quote }}
  ports:
    - port: {{ .Values.databaseService.port }}
      name: {{ .Values.databaseService.portName | quote }}
      targetPort: {{ .Values.databaseService.port }}