{{- if .Values.databaseNetworkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.databaseNetworkPolicy.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "Jerney-real-time-blog-website-chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.databaseStatefulset.podName }}
  
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.backendDeployment.podName }}
      ports:
        - protocol: TCP
          port: {{ .Values.databaseService.port }}

  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}