# Global settings
global:
  namespace: jerney-ns

################# Frontend Configuration #################

# Deployment
frontendDeployment:
  name: frontend-deployment
  replicas: 2
  podName: frontend-pod
  spec:
    securityContext:
      runAsNonRoot: true
      runAsUser: 101 # default user for nginx that is named as nginx
    image:
      repository: zohaibwarraich/jerney-frontend
      tag: "v1"
      pullPolicy: Always
    ports:
      - name: tcp
        containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 20
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 20
      timeoutSeconds: 5
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    volumeMounts:
      - name: nginx-config-volume
        mountPath: /etc/nginx/conf.d/default.conf
        subPath: default.conf
  volumes:
    - name: nginx-config-volume
      configMap:
        name: frontend-config

# Service
frontendService:
  name: frontend-service
  type: ClusterIP
  port: 80
  # nodePort: 30080

# HPA
frontendHpa:
  name: frontend-hpa
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
      selectPolicy: Max

# Nginx URL for backend proxy
frontendNginx:
  backendUrl: "http://backend-service:5000"

# Config Map
frontendConfig:
  name: frontend-config

# Network Policy
frontendNetworkPolicy:
  enabled: true
  name: frontend-network-policy

################# Backend Configuration #################

# Deployment
backendDeployment:
  name: "backend-deployment"
  replicas: 2
  podName: "backend-pod"
  livenessProbe:
    httpGet:
      path: /api/health
      port: 5000
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 5
  readinessProbe:
    httpGet:
      path: /api/health
      port: 5000
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 5
  spec:
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
    container:
      name: backend-container
      image:
        repository: zohaibwarraich/jerney-backend
        tag: "v14-da730b1"
        pullPolicy: Always
      ports:
        - name: tcp
          containerPort: 5000
      envFrom:
        - configMapRef:
            name: "backend-config"
        - secretRef:
            name: "backend-secret"
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
      volumeMounts:
        - name: tmp-dir
          mountPath: /tmp
    volumes:
      - name: tmp-dir
        emptyDir: {}

# Service
backendService:
  name: "backend-service"
  type: "ClusterIP"
  port: 5000

# HPA
backendHpa:
  enabled: true
  name: "backend-hpa"
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      policies:
        - type: Percent
          value: 100
          periodSeconds: 6
        - type: Pods
          value: 4
          periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
      selectPolicy: Max

# ConfigMap
backendConfig:
  name: "backend-config"
  dbHost: ""
  dbPort: "5432"

# Network Policy
backendNetworkPolicy:
  enabled: true
  name: "backend-network-policy"
  RdsEgress:
    cidr: "10.0.0.0/16"
    port: 5432

# External Secrets (AWS Secret Manager)
backendExternalSecret:
  name: "backend-external-secret"
  remoteKey: "prod/jerney/backend"
  spec:
    refreshInterval: 1h
    target:
      name: backend-secret

################# Infrastructure Configuration #################
infrastructure:
  EKSclusterArn: "https://kubernetes.default.svc"

  secretStore:
    enabled: true
    region: ap-south-1
    name: aws-secretsmanager

  gateway:
    enabled: true
    gatewayClassName: nginx
    name: jerney-gateway
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-internal: "false"

  httpRoutes:
    enabled: true
    name: jerney-http-route
    backendPath: /api
    frontendPath: /
    requestRedirect:
      name: jerney-http-redirect
      enabled: true

  clusterIssuer:
    enabled: true
    useStaging: false
    name: letsencrypt-route53
    email: zohaibwarraich@gmail.com
    region: ap-south-1

  certificate:
    name: jerney-tls-cert
    secretName: jerney-tls-secret
    domain: jerney.zohaibofficial.online
    dnsNames:
      - jerney.zohaibofficial.online
      - www.jerney.zohaibofficial.online

  storageClass:
    enabled: true
    name: ebs-sc
    provisioner: ebs.csi.eks.amazonaws.com
    type: gp3
    reclaimPolicy: Retain
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true

  serviceAccount:
    create: true
    name: eso-sa
    # pass arn of secret manager role that has access of secret manager.
    roleArn: null
