{{- if .Values.infrastructure.secretStore.enabled -}}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.infrastructure.secretStore.name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    {{- include "Jerney-real-time-blog-website-chart.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.infrastructure.secretStore.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.infrastructure.serviceAccount.name | quote }}
{{- end }}